### ISSUE TITLE
Last version 1.1 does not available on Maven

### ISSUE THREAD

**Issue by siabar** [dkpro/dkpro-jwktl#39]
When I add the maven dependency 
	<dependency>
	  <groupId>de.tudarmstadt.ukp.jwktl</groupId>
	  <artifactId>jwktl</artifactId>
	  <version>1.1.0</version>
	</dependency>

I got Error: Missing artifact de.tudarmstadt.ukp.jwktl:jwktl:jar:  1.1.0

What is the problem?

**Comment by chmeyer** [comment]
As of version 1.1.0, JWKTL switched to a different naming convention:

```
<groupId>org.dkpro.jwktl</groupId>
<artifactId>dkpro-jwktl</artifactId>
<version>1.1.0</version>
```

And yes, the GitHub homepage was still pointing you to the old artifact. I've corrected this now. Thanks for pointing out this problem.

**Comment by siabar** [comment]
Actually, I also tried the new one but I got Error:
<groupId>org.dkpro.jwktl</groupId>
<artifactId>dkpro-jwktl</artifactId>
<version>1.1.0</version>

Exception in thread "main" de.tudarmstadt.ukp.jwktl.api.WiktionaryException: Unable to establish a db connection
        at de.tudarmstadt.ukp.jwktl.api.entry.BerkeleyDBWiktionaryEdition.<init>(BerkeleyDBWiktionaryEdition.java:224)
        at de.tudarmstadt.ukp.jwktl.api.entry.BerkeleyDBWiktionaryEdition.<init>(BerkeleyDBWiktionaryEdition.java:203)
        at de.tudarmstadt.ukp.jwktl.JWKTL.openEdition(JWKTL.java:95)
        at de.tudarmstadt.ukp.jwktl.JWKTL.openEdition(JWKTL.java:86)
        at wikionary.InsertingMongo.main(InsertingMongo.java:33)
Caused by: com.sleepycat.persist.evolve.IncompatibleClassException: (JE 5.0.73) Mutation is missing to evolve class: de.tudarmstadt.ukp.jwktl.api.entry.WiktionaryEntry version: 0 to class: de.tudarmstadt.ukp.jwktl.api.entry.WiktionaryEntry version: 0 Error: Field is not present or not persistent: gender
---
Changes to the fields or superclass were detected when evolving class: de.tudarmstadt.ukp.jwktl.api.entry.WiktionaryTranslation version: 0 to class: de.tudarmstadt.ukp.jwktl.api.entry.WiktionaryTranslation version: 0 Error: A new higher version number must be assigned
---
(Note that when upgrading an application in a replicated environment, this exception may indicate that the Master was mistakenly upgraded before this Replica could be upgraded, and the solution is to upgrade this Replica.)
        at com.sleepycat.persist.impl.PersistCatalog.init(PersistCatalog.java:512)
        at com.sleepycat.persist.impl.PersistCatalog.initAndRetry(PersistCatalog.java:268)
        at com.sleepycat.persist.impl.PersistCatalog.<init>(PersistCatalog.java:228)
        at com.sleepycat.persist.impl.Store.<init>(Store.java:204)
        at com.sleepycat.persist.EntityStore.<init>(EntityStore.java:190)
        at de.tudarmstadt.ukp.jwktl.api.entry.BerkeleyDBWiktionaryEdition.connect(BerkeleyDBWiktionaryEdition.java:244)
        at de.tudarmstadt.ukp.jwktl.api.entry.BerkeleyDBWiktionaryEdition.<init>(BerkeleyDBWiktionaryEdition.java:222)


My code words perfectly with version 1.0.1

**Comment by chmeyer** [comment]
Most likely, you're trying to open a parsed Wiktionary version created with version 1.0.1 within a program referencing version 1.1.0. This does not work, since version 1.1.0 made several changes to the data model. It is essential to parse the Wiktionary XML dump again with version 1.1.0 in order for your program to work. This a good idea anyway, since there are usually some corrections in the parsing/extraction process in each version, which improves data quality (while there are typically little changes to the actual API).

**Comment by siabar** [comment]
OK I got it, I will parse it again with new version,

Thanks
