### ISSUE TITLE
getting  Caused by: com.sleepycat.je.UniqueConstraintException: (JE 5.0.73) Unique secondary key is already present

### ISSUE THREAD

**Issue by MikePone** [dkpro/dkpro-jwktl#48]
I get the following stack trace when trying to parse the enwiki-20180420-pages-articles.xml.bz2 dump file.  I am using the 1.1.0 version.  I will try to parse some older dump files and see what happens.

INFO: Parsed 1975000 pages
Exception in thread "main" de.tudarmstadt.ukp.jwktl.api.WiktionaryException: Unable to save page Busser
	at de.tudarmstadt.ukp.jwktl.parser.WiktionaryArticleParser.saveParsedWiktionaryPage(WiktionaryArticleParser.java:156)
	at de.tudarmstadt.ukp.jwktl.parser.WiktionaryArticleParser.onPageEnd(WiktionaryArticleParser.java:105)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at de.tudarmstadt.ukp.jwktl.parser.WiktionaryDumpParser.onPageEnd(WiktionaryDumpParser.java:190)
	at de.tudarmstadt.ukp.jwktl.parser.WiktionaryDumpParser.onElementEnd(WiktionaryDumpParser.java:151)
	at de.tudarmstadt.ukp.jwktl.parser.XMLDumpParser$XMLDumpHandler.endElement(XMLDumpParser.java:83)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1783)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2970)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
	at javax.xml.parsers.SAXParser.parse(SAXParser.java:195)
	at de.tudarmstadt.ukp.jwktl.parser.XMLDumpParser.parseStream(XMLDumpParser.java:130)
	at de.tudarmstadt.ukp.jwktl.parser.XMLDumpParser.parse(XMLDumpParser.java:121)
	at de.tudarmstadt.ukp.jwktl.parser.WiktionaryDumpParser.parse(WiktionaryDumpParser.java:78)
	at de.tudarmstadt.ukp.jwktl.JWKTL.parseWiktionaryDump(JWKTL.java:140)
	at de.tudarmstadt.ukp.jwktl.JWKTL.parseWiktionaryDump(JWKTL.java:114)
	at com.lmco.textanalysis.filereader.WiktionaryDB.main(WiktionaryDB.java:19)
Caused by: com.sleepycat.je.UniqueConstraintException: (JE 5.0.73) Unique secondary key is already present
	at com.sleepycat.je.SecondaryDatabase.insertKey(SecondaryDatabase.java:997)
	at com.sleepycat.je.SecondaryDatabase.updateSecondary(SecondaryDatabase.java:857)
	at com.sleepycat.je.SecondaryTrigger.databaseUpdated(SecondaryTrigger.java:41)
	at com.sleepycat.je.Database.notifyTriggers(Database.java:2122)
	at com.sleepycat.je.Cursor.putNotify(Cursor.java:2136)
	at com.sleepycat.je.Cursor.putNoDups(Cursor.java:2052)
	at com.sleepycat.je.Cursor.putInternal(Cursor.java:2020)
	at com.sleepycat.je.Cursor.putNoOverwrite(Cursor.java:792)
	at com.sleepycat.persist.PrimaryIndex.put(PrimaryIndex.java:402)
	at com.sleepycat.persist.PrimaryIndex.put(PrimaryIndex.java:335)
	at de.tudarmstadt.ukp.jwktl.parser.WritableBerkeleyDBWiktionaryEdition.savePage(WritableBerkeleyDBWiktionaryEdition.java:219)
	at de.tudarmstadt.ukp.jwktl.parser.WiktionaryArticleParser.saveParsedWiktionaryPage(WiktionaryArticleParser.java:149)
	... 23 more

**Comment by MikePone** [comment]
This also happens with enwiki-20180320-pages-articles.xml.bz2

Exception in thread "main" de.tudarmstadt.ukp.jwktl.api.WiktionaryException: Unable to save page Coca-Cola HBC AG
	at de.tudarmstadt.ukp.jwktl.parser.WiktionaryArticleParser.saveParsedWiktionaryPage(WiktionaryArticleParser.java:156)
	at de.tudarmstadt.ukp.jwktl.parser.WiktionaryArticleParser.onPageEnd(WiktionaryArticleParser.java:105)
	at java.lang.Iterable.forEach(Iterable.java:75)
...

**Comment by chmeyer** [comment]
Just tried en wiktionary 20180420 with JWKTL 1.1.0. It worked without problems on Linux. Are you sure that you have the right dump? Classics are using Wikipedia rather than Wiktionary... Other than that, it could be a platform issue. You could try debugging to see what happens...
